server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: qazwsx123edc
    url: jdbc:mysql://10.25.16.253:3306/jichong_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity
